### ISSUE TITLE
recipe for visual signals

### ISSUE THREAD

**Issue by judos** [Zomis/FactorioMods#17]
Hi there,
Isn't the recipe for the GUI Signal Display far too expensive? I find the item useful but it should be somewhat cheaper (similar to the combinators). I find the item should be available mid-game instead of just late game (where I don't care for much signals anymore because I have everything available everywhere anway).
What do you think? Why did you make it so expensive? Might also promote your mod a bit more, if the item is more available ;)

**Comment by Zomis** [comment]
Hi there. Yes, I am considering making it a bit less expensive. I agree that it would be more useful if it would be accessible earlier. Maybe remove the requirement of processing units and reduce the amount of advanced circuits to 20 or so? And also reduce the research cost of course.

The reason why I made it quite expensive was because of this mod which I found just had *insane* requirements: https://mods.factorio.com/mods/Fumelgo/CircuitsUI

What would your recommendation for cost be?

**Comment by Zomis** [comment]
I reduced the costs now.

Technology: Requires Circuit Network + Optics. 15 seconds, 1 red science pack + 1 green science pack (x200)
Item: 4 radar, 40 green wire, 40 red wire, 10 lamp. Total cost: 215 iron plate, 205 copper plate.

See latest release at https://mods.factorio.com/mods/zomis/visual-signals
