### ISSUE TITLE
Detected recipe change message flood

### ISSUE THREAD

**Issue by Lezreth** [Zomis/FactorioMods#26]
I keep getting the following message periodically:

[What is missing] Detected recipe change at {1077.5, -520.5} from iron-plate to copper-plate

It floods the console with a whole bunch in a row when it happens.  The numbers in the brackets changes in each flood set.  Also it alternates between 'from iron to copper' and 'from copper to iron'.

I uploaded a zip file with my save, mod list, and mod settings files (25.2MB) to google drive.  (Github's max upload size is 10MB.)
[https://drive.google.com/file/d/0Byroz2BAyLHob1FmSGZtNGhxb2M/view?usp=sharing](url)

**Comment by Zomis** [comment]
Sorry for my late reply, I have been on vacation.

This is probably because the mod also sends notifications for furnaces, so if you have furnaces that have altering responsibilities (sometimes copper, sometimes iron) I imagine this can happen quite a bit.

I will fix this in the next release by disabling this message for furnaces.

**Comment by Zomis** [comment]
This has been fixed in the latest version of "What is missing".
