### ISSUE TITLE
Advanced Combinators: Bitwise Operations?

### ISSUE THREAD

**Issue by Joshwoo70** [Zomis/FactorioMods#33]
I do not see any bitwise operations for advanced combinators, Is it possible if you could add those?

**Comment by Zomis** [comment]
Absolutely! http://lua-users.org/wiki/BitwiseOperators How many do you want? :)
bitwise-not, bitwise-xor, bitwise-and, bitwise-or definitely, would you like left/right shift/rotate as well?

**Comment by Joshwoo70** [comment]
think all of them would be a nice feature to have!

Also I'm getting a crash everytime I press Apply:

```
set_simple(1,virtual/signal-0,const(1));
set_simple(1,virtual/signal-1,const(1));
comment(Empty command);
set_signal(mod(const(1),const(1)),signal(signal_type(virtual/signal-0),const(1)));
```

**Comment by Joshwoo70** [comment]
Image log:
![factorio 2018-01-18 21 15 00 568](https://user-images.githubusercontent.com/7894419/35099942-d5696464-fc94-11e7-9632-2b6136d7c915.png)

**Comment by Zomis** [comment]
Whoops, I will need to add some boundary check there. The problem is that `mod(const(1),const(1)` evaluates to 0, which makes the command `set_signal(const(0),signal(signal_type(virtual/signal-0),const(1)));`
 which fails because the index (the first parameter to `set_signal`) needs to be within the range of 1..24. I will add a boundary check for that.

**Comment by Zomis** [comment]
This will be added in the next release, which might be within a few days.

**Comment by Zomis** [comment]
Fixed and released: https://mods.factorio.com/mod/advanced-combinator
